const allBtns = document.querySelectorAll("nav.group-nav ul li a"),
    allSections = document.querySelectorAll("main article .container>*");
let [
        allSectionsBtn,
        onlineCoursesBtn,
        interactiveTutorialsBtn,
        youtubeBtn,
        readingBtn,
        referencesBtn,
        challengesBtn,
        communitisBtn,
        toolsBtn,
        cssBtn,
        frameworksBtn,
        inspirationBtn,
        graphicsBtn,
        colorsBtn,
        typographyBtn,
        iconsBtn,
        deploymentBtn,
    ] = allBtns,
    [
        onlineCoursesSection,
        interactiveTutorialsSection,
        youtubeSection,
        readingSection,
        referencesSection,
        challengesSection,
        communitisSection,
        toolsSection,
        cssSection,
        frameworksSection,
        inspirationSection,
        graphicsSection,
        colorsSection,
        typographySection,
        iconsSection,
        deploymentSection,
    ] = allSections,
    sections = [
        onlineCoursesSection,
        interactiveTutorialsSection,
        youtubeSection,
        readingSection,
        referencesSection,
        challengesSection,
        communitisSection,
        toolsSection,
        cssSection,
        frameworksSection,
        inspirationSection,
        graphicsSection,
        colorsSection,
        typographySection,
        iconsSection,
        deploymentSection,
    ];
function clicked(e, n) {
    e.addEventListener("click", () => {
        (n.style.display = "initial"),
            sections
                .filter((e) => e != n)
                .forEach((e) => (e.style.display = "none"));
    });
}
allSectionsBtn.addEventListener("click", () => {
    sections.forEach((e) => (e.style.display = "initial"));
}),
    clicked(onlineCoursesBtn, onlineCoursesSection),
    clicked(interactiveTutorialsBtn, interactiveTutorialsSection),
    clicked(youtubeBtn, youtubeSection),
    clicked(readingBtn, readingSection),
    clicked(referencesBtn, referencesSection),
    clicked(challengesBtn, challengesSection),
    clicked(communitisBtn, communitisSection),
    clicked(toolsBtn, toolsSection),
    clicked(cssBtn, cssSection),
    clicked(frameworksBtn, frameworksSection),
    clicked(inspirationBtn, inspirationSection),
    clicked(graphicsBtn, graphicsSection),
    clicked(colorsBtn, colorsSection),
    clicked(typographyBtn, typographySection),
    clicked(iconsBtn, iconsSection),
    clicked(deploymentBtn, deploymentSection);
